-- Add tutors column to coordinaciones_tutores
ALTER TABLE coordinaciones_tutores ADD COLUMN IF NOT EXISTS tutors JSONB;

-- Add color column to documentos_descarga (if you noticed it was missing in my previous analysis, good to add)
ALTER TABLE documentos_descarga ADD COLUMN IF NOT EXISTS color TEXT;

-- Ensure tables exist (just in case they were only placeholders in policies)
CREATE TABLE IF NOT EXISTS entregables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    stage TEXT,
    title TEXT,
    deadline TEXT,
    department TEXT
);

CREATE TABLE IF NOT EXISTS documentos_descarga (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT,
    link TEXT,
    icon TEXT,
    color TEXT,
    department TEXT
);

-- Grant permissions just in case
GRANT ALL ON TABLE entregables TO anon, authenticated, service_role;
GRANT ALL ON TABLE documentos_descarga TO anon, authenticated, service_role;
GRANT ALL ON TABLE coordinaciones_tutores TO anon, authenticated, service_role;

-- Re-apply policies (Supabase sometimes needs this if table was dropped/recreated, but here strictly adding columns/tables)
-- Note: You should check allow_writes.sql for the policies again if these are new tables.
